version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rephelper
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRES_IN=86400000
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,https://rephelper.com
    depends_on:
      - db
    networks:
      - rephelper-network
    restart: always

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rephelper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rephelper-network
    restart: always

networks:
  rephelper-network:
    driver: bridge

volumes:
  postgres-data: 