global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['api:8080', 'postgres:5432']
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s 