[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/*.jar --spring.profiles.active=prod"
healthcheckPath = "/debug/info"
healthcheckTimeout = 300

[vars]
SPRING_PROFILES_ACTIVE = "prod" 