[build]
builder = "RAILPACK"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/debug/info"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[vars]
SPRING_PROFILES_ACTIVE = "prod" 