[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.simple"

[deploy]
startCommand = "sh /app/start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
type = "web"
name = "rephelper"
plan = "free"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
healthcheckInterval = 30
[services.vars]
SPRING_PROFILES_ACTIVE = "prod"
SERVER_PORT = "3000"

[vars]
SPRING_PROFILES_ACTIVE = "prod"
DB_HOST = "${{Secrets.DB_HOST}}"
DB_PORT = "${{Secrets.DB_PORT}}"
DB_NAME = "${{Secrets.DB_NAME}}"
DB_USER = "${{Secrets.DB_USER}}"
DB_PASSWORD = "${{Secrets.DB_PASSWORD}}"
JDBC_DATABASE_URL = "${{Secrets.JDBC_DATABASE_URL}}" 