[build]
builder = "NIXPACKS"
buildCommand = "chmod +x ./mvnw && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/*.jar --spring.profiles.active=prod"
healthcheckPath = "/debug/info"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[nixpacks]
install-cmd = "chmod +x ./mvnw"
start-cmd = "java -jar target/*.jar --spring.profiles.active=prod"
processes-file = "Procfile"

[vars]
SPRING_PROFILES_ACTIVE = "prod" 